### ISSUE TITLE
When i start the bot it gives me this error

### ISSUE THREAD

**Issue by DiscordLetmeIn** [ARealWant/Guildbomb#4]
`Traceback (most recent call last):
  File "C:\Users\Kevin\Documents\Guildbomb-master\Guildbomb\mainbomb.py", line 50, in <module>
    bot.run(dc_token)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 650, in start
    await self.login(*args, bot=bot)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 291, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Kevin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]
`

**Comment by ARealWant** [comment]
Hello,

you may check the token that you put in again and doublecheck if you're using the right discord.py version (latest one's currently 1.5.1).

Sincerely
ARealWant
